spring.application.name=coreJpa
# [Java 21 ?? ???(Project Loom) ???]
# ?? ??: OS ???? 1:1 ???? ??? ??? ??? ?? (?? ? ??)
# ?? ???: JVM ???? ???? ?? ???? ???? ?? ?? ?? ??? ??? ????? ??
spring.threads.virtual.enabled=true

#jasypt.encryptor.password=my_custom_secret_key
encryptor.password=my_custom_secret_key

# [?????? ?? ??]
# DB ?? ?? ? ??? ?? (KST ?? ???? ?? Asia/Seoul ??)
# ?????? ?? ?? ID
# ?????? ?? ?? ????
# ??? DB ???? ??? ?? (MySQL 8.0 ?? ?? ????)
spring.datasource.url=zItqqA6id0V29kB7lCcA6wR4fprmZ/EihEqq2R4Ws2SZKEQdZ93aFXsTOvbeLLTGmz5+U3mRFfBbSTue1wI1+Q==
spring.datasource.username=zHPSGWsLy3McqWq/Vg2p8A==
spring.datasource.password=TT6VSlaHEq7H1onZYDWUfA==
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# [JPA ? Hibernate ?? ??]
# ?????? ?? ? ??? ????? DB ???? ???? ?? (?? ??: update / ?? ??: none ?? validate ??)
spring.jpa.hibernate.ddl-auto=update
# ???? ?? SQL ??? ???? ??
spring.jpa.show-sql=true
# ? ?? ???? SQL? ?? ?? ??(????)?? ??
spring.jpa.properties.hibernate.format_sql=true
# ??? ???? SQL ??? ??? ?? ??? ?? (?? 21/?? 3.x ?? ??)
spring.jpa.properties.hibernate.highlight_sql=true

# [?? ? ??? ??]
# Hibernate? ???? SQL ?? ??? DEBUG? ??
logging.level.org.hibernate.SQL=DEBUG
# SQL? ????? ????(PreparedStatement? ?) ??? ??? ?? ?? (TRACE ??)
logging.level.org.hibernate.orm.jdbc.bind=TRACE

server.port=${PORT:8080}